---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: v1.4.6
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 1m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  timeout: 20m
  values:
    image:
      tag: v1.4.7
    csi:
      enableCephfsDriver: false
    registrar:
      image: raspbernetes/csi-node-driver-registrar:1.3.0
    provisioner:
      image: raspbernetes/csi-external-provisioner:1.6.0
    snapshotter:
      image: raspbernetes/csi-external-snapshotter:2.1.1
    attacher:
      image: raspbernetes/csi-external-attacher:2.2.0
    resizer:
      image: raspbernetes/csi-external-resizer:0.5.0
