---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  type: discord
  channel: notifications
  secretRef:
    name: discord-provider
