---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: gotk-system
      interval: 1m
  # Depends on having the sealed secret cloudflare-cert-manager-token
  # un-encrypted. Also depends on prometheus-operator due to service monitor
  # resources.
  dependsOn:
    # - name: sealed-secrets
    #   namespace: kube-system
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    extraArgs:
      - "--dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53"
