---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.1.27
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: gotk-system
      interval: 1m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  # Depends on kube-prometheus-stack due to service monitor resources.
  # dependsOn:
  #   - name: kube-prometheus-stack
  #     namespace: monitoring
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.4
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.4
    prometheus:
      serviceMonitor:
        enabled: true
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.45.100-192.168.45.105
