# ---
# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#   name: prometheus
#   namespace: monitoring
#   annotations:
#     external-dns.alpha.kubernetes.io/target: ingress.milton.mcf.io
# spec:
#   hosts:
#     - istio-prometheus.milton.mcf.io
#   gateways:
#   - monitoring/istio-ingressgateway
#   http:
#     - match:
#         - port: 443
#       route:
#         - destination:
#             port:
#               number: 9090
#             host: z-prometheus.monitoring.svc.cluster.local
