apiVersion: ENC[AES256_GCM,data:TcI=,iv:7pqOcVOeEuKT2hT/1fL699USUk3ndZME+zylL1Dt6JI=,tag:fZddqtbrTjsCPq8zGPA/dQ==,type:str]
kind: ENC[AES256_GCM,data:YXeTvQmr,iv:C3nUIaoibOuWzM5zY0BkXzVyv/YP0gBHcv01RoKS/Wo=,tag:r7k2kzyltRBdl70rjMCxYA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l/qUSE0IKcZ06Afw5Xjc1AMqWKNqtoNG2U8=,iv:rJ3nk/n/YbkFFoLYEfDI2yeVpB7aj15iA2lG8zmOdiY=,tag:CFc0CIsIw9mCMujvn1nnIg==,type:str]
    namespace: ENC[AES256_GCM,data:lOOAb8njscFNQ9Jo,iv:WWsVmn0XL8nHuZRVX0WfWGsl6BYaC7Jh/ladWS84/8Y=,tag:FobQwpfwUFwu8/gGhamzBQ==,type:str]
type: ENC[AES256_GCM,data:dFv8s1IZ,iv:/mVPU0SnTrVHfEC9paOzXf+zxUh2mdmb7ZUBvllEz5s=,tag:YORoCC85wnUckTgDiUqfEA==,type:str]
data:
    cloudflare_api_token: ENC[AES256_GCM,data:xIDwRwAvEcRwp8N3FmB2W+2JdRY5KDa4qpajOSK0JfZii3rdbpFiEcW9CUlEMyQebQxY01EqeD8=,iv:9mFt0Ucx1bNH7MQ7pLW4uWt75OhU/f073cAtP8aRQ9w=,tag:BeFXbGdmCuTmhvUVR3RAOg==,type:str]
    cloudflare_hosts: ENC[AES256_GCM,data:xm0HcO/6w06OGoF7O3kt5+vwPrk=,iv:kkhHOOd1cIBYA1USacmhRWoFTLa9gTw5pKJiGWQSv3A=,tag:OzN7Ap1kvOP8BEuG/JMCzg==,type:str]
    cloudflare_record_types: ENC[AES256_GCM,data:kGgqzQ==,iv:UKBLp+7xiegFLRwnQ7HD80id+1eTRN3PY8f0LaphwSM=,tag:oZD848pTwMF51JTa3Djv1g==,type:str]
    cloudflare_zones: ENC[AES256_GCM,data:GZ/GQCsmIkmHvbrD/NpAmZXNkuCwZKQ3gNb9hMINwk2ykSZhHTSLfhsJwiU=,iv:FFTxj9RtTYIziWS9ZQVkOTJmOZ6567JV4UGilllem6E=,tag:S7ciO2JXzq2XJW7TNID0hQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-11-04T04:13:26Z'
    mac: ENC[AES256_GCM,data:3wWkcBzamgD0jsPhBS+/txaM0clAJaZEhgRUfazmFMD5qEv5FQesVGGeDHgj52hi5XGIRGYWBWQw118tSWJp1EQMfgq7fB5x7o3nHTsHifflDAZ5+tc+OsaTM1y5A+vc4bBu7dcjhxsz8ebFFY4qISI2ukUXGVP4cMmUZCdPsMY=,iv:4ZRpDRc7yFTMBzLRQuejJzFtTYcbvqsHsWGwi7Kx7NQ=,tag:/luvGILTxdwHhqZHif49Zw==,type:str]
    pgp:
    -   created_at: '2020-11-04T04:13:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//Y/2bUHaNXVipupdhq5ikdvVEYxXrBKZ0MFIT5qDHWBxe
            sevoySUQkPUXbXPHVOXzWzj8j0fLRZOjcVgIj+PjcZ54E43ffTNVWqJd3teDqDvo
            znjaksX13Kgg3URSFA3l6svFsq6VjZOw16xPPYm0kdA4cd7XFYtMFihyqxYu+WUs
            4jA5uQ4Q2B1iU/FvEwXa8N1jiahzm3HQrW7J7/eB5D3G/fbVF7v/nUOWt1R+8epW
            pPw/1xHXkeoDP0Mo7Xt0LK+VZJaWBzdJf6jmdinHu3Xl9JPM8N1LmdoUOqQRPuXE
            Ge6YSPFyZBYmtRT4coEXq7boLwEHbnU8UqSWfGH4CkRFUdmLx5V1TZ5ScFCeT2qo
            dVemHdn7EMLkULaQxk49uSU3XNzZgWN5FUqkTKjgySHESPFI1rRyAUjsonBJy9Fj
            WQ3fFib68V7rSCdFxCp7Pz5QYZCyxVZ+gMD11G8/KWgtIK31li9VBnHGC1nnDMy5
            hNs71lz8Yhvjl6LKI0TENYtZu8RfJIZfHSRU5QIBwEEY1Se/XPv4IImCgcuj7Dxb
            rcvHe+yhyBuzUTt/oWecpP6oBWkggK7sJm9sFaB59UnGoZXcCNEibHHPGX8d0qjp
            c/26fyymguAdLgDJ4GVyewtMywmHKAttzg5Ygf96pmJIq6OEg5Q7Yndt3UItT+DS
            XAEJ5lfacYEQef8pmEHwybSNt2kmGiSlxnsc/zAvYr/hG3CJY/Mm/YQ5ZIc87d8g
            7qVUtuGJ1g5MBZ87M8hpYacgt4Tl+C2liBKrPcbvXNGQWLUx2rjIRSB+dem5
            =L0Oe
            -----END PGP MESSAGE-----
        fp: EE2DF7502917345D1EB1749ED7005BCAECF9D003
    unencrypted_suffix: _unencrypted
    version: 3.6.1
